// build_options: 
Introduction
============
Arnauld Van Muysewinkel <avm@pendragon.be>
v0.1, 07-Dec-2016: Draft version
:backend: slidy
:data-uri:
ifdef::env-build[:icons: font]
:extension: adoc
//extension may be overriden by compile.sh
ifeval::["{extension}"!="pdf"]
:doctitle: Web Performance Tuning - {doctitle}
:lastpage: lastpage.adoc.include
endif::[]
:copyright: Creative-Commons-Zero (Arnauld Van Muysewinkel)

Content
-------

* <<_introduction,Introduction>>

_(link:0.1-training_plan.{extension}#_introduction[back to course plan])_


Why should we optimize websites?
--------------------------------

* Improve user experience
* Improve page ranking (SEO)
* Mobile compliance
* UI logic is shifting to the front-end => increasing complexity

Some figures:

* 94.4% of web sites use JavaScript (as of 2016-Dec)
* users abandon a web site after 2s of waiting
* 90% of the waiting time is spent *after* the HTML has been retrieved
* 80% of the waiting time is spent *in* the front-end


Scope
-----

"Transport" section:

* all kinds of web apps

"CPU" and "Memory" sections:

* Web apps with browser side logic
** traditional (eg JSF) with "smart" components, AJAX...
** SPA (Single Page Apps)
* i.e. applications relying heavily on JavaScript

Out-of-scope:

* animations, games...


Other
-----

* Rule for optimizing web sites and frequent issues
* Why should we optimize websites?
* Diagnose performance issues in the browser

* Diagnostic tools - workshop
* Identify and apply best practices and rules to make web applications efficient


Exercises
---------

Chrome - Blink(WebKit) - V8


https://developers.google.com/web/fundamentals/performance/

// http://desalasworks.com/article/javascript-performance-techniques/

Disclaimer
----------

TODO


include::{lastpage}[]
