// build_options: 
Objectives
==========
Arnauld Van Muysewinkel <avm@pendragon.be>
v0.1, 07-Dec-2016: Draft version
:backend: slidy
:data-uri:
ifdef::env-build[:icons: font]
:extension: adoc
//extension may be overriden by compile.sh
ifeval::["{extension}"!="pdf"]
:doctitle: Web Performance Tuning - {doctitle}
:lastpage: lastpage.adoc.include
endif::[]
:copyright: Creative-Commons-Zero (Arnauld Van Muysewinkel)


Content
-------

* <<_motivations,motivations>>
* <<_objectives,objectives>>

_(link:0.1-training_plan.{extension}#_introduction[back to course plan])_


Motivations
-----------

* constant growth of mobile and responsive applications
* applications increasingly rich and massively JavaScript
* users demanding high standard response times

Performance issues reside not only on the server side, +
but also in the behavior of the web front-end.


Objectives
----------

The objectives of this training course are:

- to give basic knowledge of the internal working of the browsers
- to propose a methodology for optimizing performance
- to provide the best practices and tools necessary for this optimization

At the end of the course, the participant should be able to solve most frequent performance issues on its own.


include::{lastpage}[]
