// build_options: 
Performance improvement process
===============================
Arnauld Van Muysewinkel <avm@pendragon.be>
v0.1, 07-Dec-2016: Draft version
:backend: slidy
:data-uri:
ifdef::env-build[:icons: font]
:extension: adoc
//extension may be overriden by compile.sh
ifeval::["{extension}"!="pdf"]
:doctitle: Web Performance Tuning - {doctitle}
:lastpage: lastpage.adoc.include
endif::[]
:copyright: Creative-Commons-Zero (Arnauld Van Muysewinkel)

Content
-------

* <<_general_recommendations,General recommendations>>
* <<_improvement_process,Improvement process>>

_(link:0.1-training_plan.{extension}#_preamble[back to plan])_


General recommendations
-----------------------

* no premature optimization
* must have a performance objective
* should have a workbench (performance test)
* "80-20": concentrate of the 20% of the app that is responsible for 80% of the load
* one issue often hides other issues
* first actions might not show any improvement. +
Yet, don't despair!


Improvement process
-------------------

* run test
* measure
* if performance objective not reached:
** analyse results, look for:
*** transport issues,
*** then GC issues,
*** then CPU/code optimization
** fix (one at a time!)
** iterate (-> run test)


Performance test
----------------

Test data::
* test with various parameters, especially corner cases

Test harness::
* properly isolated
* test in real-life conditions:
** network (bandwidth and latency)
** server load (does impact response time)
** browser brand and version
** client device type (desktop, mobile phone...) and sizing (CPU, RAM...)

Test scenario::
* representative of the issue


Monkey testing
--------------

* Lot's of random actions (automated)

-> objective is to make sure there is no way the app could crash

(see http://www.redotheweb.com/2014/01/07/completing-the-js-test-stack-introducing-greminsjs.html)
-> https://github.com/marmelab/gremlins.js


Other topics
------------

http://superherojs.com/#performance


include::{lastpage}[]
