// build_options: 
Tuning transport issues
=======================
Arnauld Van Muysewinkel <avm@pendragon.be>
v0.0, 07-Dec-2016: Draft version
:backend: slidy
:data-uri:
ifdef::env-build[:icons: font]
:extension: adoc
//extension may be overriden by compile.sh
ifeval::["{extension}"!="pdf"]
:doctitle: Web Performance Tuning - {doctitle}
:lastpage: lastpage.adoc.include
endif::[]
:copyright: Creative-Commons-Zero (Arnauld Van Muysewinkel)

Content
-------

* <<_axis,Most frequest improvement axis>>
* <<_investigation_tools,Investigation tools>>
* <<_pwa,Progressive Web Apps>>
* <<_http_2,HTTP/2>>

_(link:0.1-training_plan.html#_transport[back to plan])_


[[_axis]]
Most frequent improvement axis
------------------------------

* Reduce HTTP requests count
* Use client-side processing
* (Parallelize requests)
* Use caches
* Reduce sizes
* (Use a Global Network)
* Optimize depending on the context
* Reduce first rendering latency
* Optimize on the server side


Reduce HTTP requests count
--------------------------

* combine small images into one
* combine several scripts as one
* combine several stylesheet as one
* avoid duplicate scripts


Use client-side processing
--------------------------

* validations
* ...

//
//Parallelize requests
//--------------------
//

Use caches
----------

* +Expires+ header
* +ETag+ header
* make scripts and stylesheets external


Reduce sizes
------------

* minification of scripts and stylesheets
* compression of HTTP payload

Example: Angular.js

* minification: 729 KB -> 101 KB
* gzip compression: 101 KB -> 37 KB


(Use a Global Network)
----------------------

* CDN (Content Delivery Network or Content Distribution Network)
* globally distributed network of proxy servers deployed in multiple data centers

Goal: Serve content to end-users with:

* high availability
* high performance


Optimize depending on the context
---------------------------------

Context:

* device
* bandwidth

-> adapt size of resources (images) +
-> adapt complexity of page


Reduce first rendering latency
------------------------------

* stylesheets at the top
* scripts at the bottom


Optimize on the service side
----------------------------

* https://www.nginx.com/blog/10-tips-for-10x-application-performance/

Investigation tools
-------------------

* Timeline
* Boomerang
* Online tools
* Lighthouse


Timeline
--------


Boomerang
---------



Online tools
------------


Lighthouse
----------

* Chrome extension: +
  https://github.com/GoogleChrome/lighthouse

-> verify criterias defined by the PWA specification (see further),
and give a global evaluation (/ 100 points)

[[_pwa]]
Progressive Web Apps (PWA)
--------------------------

*-> Bring user experience of native apps to web apps*

This is made possible by modern web technologies

According to Google, they must have the following characteristics:

progressive - responsive - work offline - app-like - fresh - safe -
discoverable - re-engageable - installable - linkable

https://developers.google.com/web/progressive-web-apps/


HTTP/2
------

Reduce latencies through:

* Data compression of HTTP headers
* HTTP/2 Server Push
* Pipelining of requests
* Multiplexing multiple requests over a single TCP connection

-> a number of current practices should disappear


Other topics
------------

* Guidelines REST (cf site SOA)


include::{lastpage}[]
