// build_options: 
Memory (garbage collector)
==========================
Arnauld Van Muysewinkel <avm@pendragon.be>
v0.0, 07-Dec-2016: Draft version
:backend: slidy
:data-uri:
ifdef::env-build[:icons: font]
:extension: adoc
//extension may be overriden by compile.sh
ifeval::["{extension}"!="pdf"]
:doctitle: Web Performance Tuning - {doctitle}
:lastpage: lastpage.adoc.include
endif::[]
:copyright: Creative-Commons-Zero (Arnauld Van Muysewinkel)
:q: '

Content
-------

* <<_memory_leaks,Memory leaks>>
** <<_global_variables,Global variables>>
** <<_timers_or_callbacks,Timers or Callbacks>>
** <<_detached_nodes,Detached nodes>>
** <<_closures,Closures>>
* <<_detection_techniques,Detection techniques>>
** <<_timeline_recording,Timeline recording>>
** <<_heap_snapshot,Heap snapshot>>
** <<_allocation_timeline,Allocation timeline>>
** <<_allocation_profiler,Allocation profiler>>
** <<_three_snapshots,3 snapshots technique>>

_(link:0.1-training_plan.html#_processing[back to plan])_


Memory leaks
------------

* memory leak = some objects are kept in memory, even though not used anymore
* due to some hanging reference _somewhere_

Most frequent causes:

* global variables
* timers or callbacks
* detached nodes (out of DOM references)
* closures


[[_global_variables]]
Leak cause: Global variables
----------------------------

* global variable in a web page = member of the +window+ object
* won't be collected as long as the page is active
* typically due to wrong usage of variable scope in functions


Leak cause: Global variables
----------------------------

*Default scope*

[source,javascript]
-----
function foo(arg) {
    bar = "this is a hidden global variable";
}
-----

is equivalent to:

[source,javascript]
-----
function foo(arg) {
    window.bar = "this is a hidden global variable";
}
-----


Leak cause: Global variables
----------------------------

*Wrong usage of +this+*

[source,javascript]
-----
function foo(arg) {
    this.bar = "this is a hidden global variable";
}
-----

is also equivalent to:

[source,javascript]
-----
function foo(arg) {
    window.bar = "this is a hidden global variable";
}
-----


Leak cause: Global variables
----------------------------

*Tricky usage of +this+*

Given:
[source,javascript]
-----
var car = {
  brand: "Nissan",
  setBrand: function(_brand) { this.brand = _brand; }
};

var setCarBrand = car.setBrand;
-----

[source,javascript]
-----
setBrand("Toyota");
-----

is equivalent to:

[source,javascript]
-----
window.brand = "Toyota"
-----

Solution:
[source,javascript]
-----
var setCarBrand = car.setBrand.bind(car);
-----


[[_timers_or_callbacks]]
Leak cause: Timers or Callbacks
-------------------------------

*Callbacks and cyclic references*

Let's consider:
[source,javascript]
-----
var element = document.getElementById('button');
function onClick(event) { element.innerHtml = 'text'; }
element.addEventListener('click', onClick);
// Do stuff
-----

We have a loop of references: +
+element+ -> +{q}click{q}+ event -> +onClick+ function -> +element+

Some (old) browsers do not collect those cyclic references well.

Solution: remove the callback before disposing the +element+:
[source,javascript]
-----
// Now we are about to remove element
element.removeEventListener('click', onClick);
element.parentNode.removeChild(element);
-----


Leak cause: Timers or Callbacks
-------------------------------

*Timers*

Let's consider:
[source,javascript]
-----
var someResource = ...
setInterval(function() {
  var element = document.getElementById('button');
  if (element) {
    // Do stuff with element and someResource, eg:
    element.innerHTML = someResource.toHtml();
}, 1000)
-----

The references graph is like this: +
interval -> +setInterval+ handler function -> +element+ and +someResource+

Even if the button (referenced through +element+) is removed,
the handler (+setInterval+) won't be collected, since the interval is still active.
Hence, +someResource+ cannot be collected.

Solution: disable the interval when removing the button.


[[_detached_nodes]]
Leak cause: Detached nodes
--------------------------

* DOM nodes stored in data structure
* the reference in the data structure is not removed when the DOM node is removed

For example:
[source,javascript]
-----
var elements = {
    buttonElt: document.getElementById('button'),
    imageElt: document.getElementById('image')
};

function doStuff() {
    elements.imageElt.src = 'http://some.url/image';
    elements.buttonElt.click();
}
-----

References graph: +
- DOM -> +{q}button{q}+ and +{q}image{q}+ elements +
- +doStuff+ function -> +elements+ +
. .  -> +buttonElt+ -> +{q}button{q}+ element +
. .  -> +imageElt+ -> +{q}image{q}+ element

Even if we remove the button:
[source,javascript]
-----
document.body.removeChild(document.getElementById('button'));
-----
it won't be collected, because there is still a reference chain
through the +buttonElt+ reference stored in +elements+.


Leak cause: Detached nodes
--------------------------

Even worst:
[source,javascript]
-----
var elements = {
    tableCell: document.getElementById('td-3-7')
    // where 'td-3-7' is the id of a <td> element inside a big <table>
};
document.body.removeChild(document.getElementById('tab'));
// where 'tab' is the id of this big <table>
-----

Even though only one small reference is held by +elements+,
the whole table will stay stuck in memory.

Indeed, before the remove, the reference graph is as follows: +
DOM -> +{q}tab{q}+ <table> -> ... -> +{q}td-3-7{q}+ <td> element -> +{q}tab{q}+ <table> +
+elements+ -> +tableCell+ -> +{q}td-3-7{q}+ <td> element -> ...

(since each table element holds a reference to the table itself!)


[[_closures]]
Leak cause: Closures
--------------------

A _closure_ is an anonymous function that capture variables *from parent scopes*.

Because of this property, they can be the cause of memory leaks in very specific cases
(see <<_exercise_closure_leak,exercise>>).

More info: http://info.meteor.com/blog/an-interesting-kind-of-javascript-memory-leak


Detection techniques
--------------------

* timeline recording
* heap snapshot
* allocation timeline
* allocation profiler


[[_timeline_recording]]
Technique: Timeline recording
-----------------------------

-> heap size over time


[[_heap_snapshot]]
Technique: Heap snapshot
------------------------

-> capture whole heap


[[_allocation_timeline]]
Technique: Allocation timeline
------------------------------

-> allocation over time


[[_allocation_profiler]]
Technique: Allocation profiler
------------------------------

-> allocation by JavaScript function


[[_three_snapshots]]
Technique of the 3 snapshots
----------------------------



Exercise: Detached nodes
------------------------

[source,html]
.detachedDOM.html
-----
include::../js/detachedDOM.html[]
-----


Exercise: Closure leak
----------------------

[source,html]
.closureLeak.html
-----
include::../js/closureLeak.html[]
-----


References
----------

* Fixing Memory Leaks in AngularJS and other JavaScript Applications. Blog post on dwmkerr.com.
http://www.dwmkerr.com/fixing-memory-leaks-in-angularjs-applications/
* http://stackoverflow.com/questions/19621074/finding-javascript-memory-leaks-with-chrome
* BloatBusters: Eliminating memory leaks in Gmail. https://docs.google.com/presentation/d/1wUVmf78gG-ra5aOxvTfYdiLkdGaR9OhXRnOlIcEmu2s/pub
// https: //docs.google.com/presentation/d/1wUVmf78gG-ra5aOxvTfYdiLkdGaR9OhXRnOlIcEmu2s/pub?start=false&loop=false&delayms=3000&slide=id.g1d65bdf6_0_0
** > https://docs.google.com/presentation/d/1wUVmf78gG-ra5aOxvTfYdiLkdGaR9OhXRnOlIcEmu2s/pub?start=false&loop=false&delayms=3000&slide=id.g14717ff3_0_23[So you found a leak. Now what?]
* https://developers.google.com/speed/articles/optimizing-javascript#avoiding-browser-memory-leaks
* Official blog of the V8 JavaScript engine. http://v8project.blogspot.be/
** Jank Busters +
// http://v8project.blogspot.be/2015/10/jank-busters-part-one.html + // mostly applicable for animations, not in our scope
   http://v8project.blogspot.be/2016/04/jank-busters-part-two-orinoco.html
** Fall cleaning: Optimizing V8 memory consumption. 2016-10-07. +
   http://v8project.blogspot.be/2016/10/fall-cleaning-optimizing-v8-memory.html

https://developers.google.com/web/tools/chrome-devtools/memory-problems/

https://auth0.com/blog/four-types-of-leaks-in-your-javascript-code-and-how-to-get-rid-of-them/

TODO
----


include::{lastpage}[]
